//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appswindows
{
    using System;
    using System.Collections.Generic;
    
    public partial class achat
    {
        public int id_achat { get; set; }
        public System.DateTime date_achat { get; set; }
        public decimal qte_achat { get; set; }
        public int id_produit { get; set; }
        public int id_fornisuer { get; set; }
        public int id_emplyee { get; set; }
        public string note_achat { get; set; }
    
        public virtual emplyee emplyee { get; set; }
        public virtual fornisuer fornisuer { get; set; }
        public virtual produit produit { get; set; }
    }
}
